### ISSUE TITLE
[Task] [Optimization] Optimizing Deprecated React Lifecycle

### ISSUE THREAD

**Issue by VampireAchao** [apache/shenyu-dashboard#341]
## Description

see：
https://legacy.reactjs.org/blog/2018/03/27/update-on-async-rendering.html

There are so many warnings indicating that we should use the new lifecycle instead of the old one, so I think it's necessary to split it into multiple tasks and make the changes one by one.

<img width="1728" alt="image" src="https://github.com/apache/shenyu-dashboard/assets/52746628/9a79cf1e-c8cc-4474-a495-0e986a066c54">

## Task List

- [x] src/routes/System/Alert/index.js
- [x] src/components/Authorized/PromiseRender.js
- [x] src/components/CountDown/index.js
- [x] src/components/Login/LoginTab.js
- [x] src/components/SideMenu/SideMenu.js
- [x] src/routes/Plugin/Common/Rule.js
- [x] src/routes/Sytem/Resources/index.js
- [x] src/utils/AuthRoute.js
- [x] src/routes/System/AppAuth/index.js
- [x] src/routes/System/Dict/index.js
- [x] src/routes/System/Metadata/index.js
- [x] src/routes/System/Plugin/index.js
- [x] src/routes/System/PluginHandle/index.js
- [x] src/routes/Plugin/Common/Selector.js  @eurecalulu 
- [x] src/routes/System/Role/index.js
- [x] src/routes/System/User/index.js
- [x] src/routes/System/User/DataPermModal.js
- [x] src/utils/AuthButton.js

**Comment by eurecalulu** [comment]
Please assign src/routes/Plugin/Common/Rule.js and src/routes/Plugin/Common/Selector.js to me~
